[package]
name = "metal-gpu"
version = "0.1.0"
edition = "2024"

[lib]
path = "lib.rs"
name = "metal_gpu"

[dependencies]
wgpu.workspace = true
winit.workspace = true
glam.workspace = true
pollster.workspace = true
